services:
  eventloop:
    image: anirudhsudhir/eventloop:1.0.0
    ports:
      - "8080:8080"
    volumes:
      - /home/sudhir/eventloop:/app/data
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/sudhir/.docker/config.json:/config.json
    command: --interval 30
