name: Pull request check workflow

on:
  push:
    branches:
      - main
jobs:
  code-check:
    uses: ./.github/workflows/code_check_flow.yaml
  build:
    needs: code-check
    uses: ./.github/workflows/docker_image_build_flow.yaml
